### ISSUE TITLE
COCO pre-trained models

### ISSUE THREAD

**Issue by shinya7y** [zehuichen123/DDOD#4]
Hi! Awesome work!
Do you have any plans to upload COCO weights?

Especially,
* ATSS(IoU) R-50 1x
* DDOD R-50 1x
* DDOD R2-101-DCN 2x
* DDOD-X R2-101-DCN 2x

It would be great if you also could provide configs for DDOD-X because the arXiv v1 seems to lack the explanation of DDOD-X and the details of multi-scale testing and stronger data augmentation.

**Comment by zehuichen123** [comment]
Currently, we don't have plans for that (the checkpoints are missing due to personal reasons), but you can run them on your own. For detailed settings about DDOD-X, you may refer to `https://github.com/hyz-xmaster/VarifocalNet/blob/master/configs/vfnet/vfnetx_r2_101_fpn_mdconv_c3-c5_mstrain_59e_coco.py`. We adopt a similar setting in this config.

**Comment by shinya7y** [comment]
Thank you for the information!
